name: 'Get git metadata'
description: 'Get the sha and version metadata from git'
author: 'Contiamo GmbH'
branding:
  icon: 'anchor'
  color: 'blue'

outputs:
  shortSHA:
    description: 'output from git rev-parse --short HEAD'
  semvar:
    description: 'semvar value based on the git describe data, similar to https://github.com/mdomke/git-semver'

runs:
  using: 'node12'
  main: 'dist/index.js'
